using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Atlanta.Info.PlayersScore;

[GenerateTypedNameReferences]
public sealed partial class PlayerScoreStatsEntry : ContainerButton
{
    public PlayerScoreStatsEntry(string nickname, int winScore, int kills)
    {
        RobustXamlLoader.Load(this);

        NicknameLabel.Text = nickname;
        WinScore.Text = winScore.ToString();
        KillScore.Text = kills.ToString();
    }

    public string? NicknameText => NicknameLabel.Text;
    public int WinScoreInt => int.Parse(WinScore.Text ?? "0");
    public int KillScoreInt => int.Parse(KillScore.Text ?? "0");
}
